export const DrivingActionTypes={
    
    ALL_DRIVING:"ALL_DRIVING",
    SELECTED_DRIVING:"SELECTED_DRIVING",
    REMOVED_DRIVING:"REMOVED_DRIVING",
    CREATE_DRIVING: "CREATE_DRIVING",
    CREATE_DRIVING_SUCCESS:"CREATE_DRIVING_SUCCESS",
    CREATE_DRIVING_FAILURE:"CREATE_DRIVING_FAILURE",

    
};